# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'europe-west6-docker.pkg.dev/crm-incoming-data-and-enrich/cloud-run-source-deploy/gcr-cleaner:latest'
    # Use the Dockerfile from inside the gcr-cleaner submodule directory
    - '--file'
    - 'gcr-cleaner/Dockerfile'
    # Set the build context to the gcr-cleaner submodule directory
    - 'gcr-cleaner/'

# Explicitly declare the image that this build produces
images:
- 'europe-west6-docker.pkg.dev/crm-incoming-data-and-enrich/cloud-run-source-deploy/gcr-cleaner:latest'
