steps:
# Step 0: Print the contents of this file to the log for debugging.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "--- Displaying contents of cloudbuild.yaml being used by this trigger ---"
    cat cloudbuild.yaml
    echo "-----------------------------------------------------------------------"

# Step 1: Initialize the submodule and build the image.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    git submodule update --init --recursive
    cd gcr-cleaner && docker build \
      --build-arg BUILDPLATFORM=linux/amd64 \
      -t 'europe-west6-docker.pkg.dev/crm-incoming-data-and-enrich/cloud-run-source-deploy/gcr-cleaner:latest' \
      --file docker/cli.dockerfile \
      .

images:
- 'europe-west6-docker.pkg.dev/crm-incoming-data-and-enrich/cloud-run-source-deploy/gcr-cleaner:latest'

options:
  logging: 'CLOUD_LOGGING_ONLY'
