steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/crm-incoming-data-and-enrich/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA', '.']

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/crm-incoming-data-and-enrich/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'marketdata-gcp-scripts'
      - '--image'
      - '...'
      - '--region'
      - 'europe-west6'
      - '--allow-unauthenticated' # Add this flag

# --- The modern, secure configuration ---

# 1. Specify the dedicated, least-privilege service account
serviceAccount: 'projects/crm-incoming-data-and-enrich/serviceAccounts/cloud-build-deployer-sa@crm-incoming-data-and-enrich.iam.gserviceaccount.com'

# 2. Specify the logging behavior (required for custom service accounts)
options:
  logging: 'CLOUD_LOGGING_ONLY'

# Optional: Define substitutions for cleaner code.
# You can set these in your Trigger configuration.
substitutions:
  _SERVICE_NAME: 'marketdata-gcp-scripts'
  _REGION: 'europe-west6' # Example: Zürich
  _REPO_NAME: 'cloud-run-source-deploy'
  _IMAGE_NAME: 'marketdata-gcp-scripts-image'
