steps:
# This single step performs both the submodule checkout and the docker build.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # First, initialize the submodule to fetch the source code
    git submodule update --init --recursive

    # Then, change into the submodule's directory and run the build from there.
    # The '&&' ensures the docker build only runs if the 'cd' is successful.
    cd gcr-cleaner && docker build \
      -t 'europe-west6-docker.pkg.dev/crm-incoming-data-and-enrich/cloud-run-source-deploy/gcr-cleaner:latest' \
      .

# Explicitly declare the image that this build produces.
images:
- 'europe-west6-docker.pkg.dev/crm-incoming-data-and-enrich/cloud-run-source-deploy/gcr-cleaner:latest'

# This 'options' block is required when using a custom service account.
options:
  logging: 'CLOUD_LOGGING_ONLY'